frontEnd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('datatable/', TemplateView.as_view(template_name = "datatable.html"), name="datatable"),
    path('', include('services.urls', namespace='Services')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

services/urls.py
from django.urls import path
from .views import *
from .activites.views import *
from .auditeurs.views import *
from .catalogue_de_formation.views import *
from .categories_de_documents.views import *
from .controles.views import *
from .corps_de_controles.views import *
from .document.views import *
from .documents.views import *
from .evaluations_impact_risque.views import *
from .execution.views import *
from .famille_de_risques.views import *
from .filiale.views import *
from .finalisation.views import *
from .formation.views import *
from .gestions_des_filiales.views import *
from .gravite_de_risques.views import *
from .initialisation.views import *
from .liste_de_documents.views import *
from .matrice_de_competence.views import *
from .matrice_de_competence_param.views import *
from .menu_auditeur.views import *
from .mise_a_jour_tpa.views import *
from .mission.views import *
from .parametrages_filiale.views import *
from .pole.views import *
from .processus.views import *
from .profil_auditeur.views import *
from .profils.views import *
from .profil_utilisateur.views import *
from .repertoire_racine.views import *
from .reporting.views import *
from .risques.views import *
from .signIn.views import *
from .statistiques.views import *
from .stats.views import *
from .suivi_des_recommandations.views import *
from .suivi_plan_de_couverture.views import *
from .superAdmin.views import *
from .transmission_justificatifs.views import *
from .type_de_missions.views import *
from .site.views import *
from .systeme.views import *
from .sys_processus.views import *
from .utilisateurs.views import *
from .planaudit.views import *

app_name = 'services'
urlpatterns = [
    path('login/', signIn, name='signIn'),
    path('', homeDashboard, name='home_superAdmin'),
    # path('', adminAsFiliale, name='homeAdminFiliale'),
    path('gestion-filiale_sAdmin/', gestFilialeSAdmin, name='gestion_filiale_admin'),
    path('authentication/logout/', deconnexion, name='deconnexion'),
    path('profil/', profil, name='profil'),
    path('change_password/', change_password, name='change_password'),
    path('reset_password/<int:pk>', reset_password, name='reset_password'),

    # activites
    path('activites', activites, name='activites'),
    path('list_activites', list_activites, name='list_activites'),
    path('add_activites', add_activites, name='add_activites'),
    path('edit_activites/<int:pk>', edit_activites, name='edit_activites'),
    path('del_activites/<int:pk>', del_activites, name='del_activites'),

    # auditeurs
    path('auditeurs', auditeurs, name='auditeurs'),
    path('list_auditeurs', list_auditeurs, name='list_auditeurs'),
    path('add_auditeurs', add_auditeurs, name='add_auditeurs'),
    path('edit_auditeurs/<int:pk>', edit_auditeurs, name='edit_auditeurs'),
    path('del_auditeurs/<int:pk>', del_auditeurs, name='del_auditeurs'),

    # catalogue_de_formation
    path('catalogue_de_formation', catalogue_de_formation, name='catalogue_de_formation'),
    path('list_catalogue_de_formation', list_catalogue_de_formation, name='list_catalogue_de_formation'),
    path('add_catalogue_de_formation', add_catalogue_de_formation, name='add_catalogue_de_formation'),
    path('edit_catalogue_de_formation/<int:pk>', edit_catalogue_de_formation, name='edit_catalogue_de_formation'),
    path('del_catalogue_de_formation/<int:pk>', del_catalogue_de_formation, name='del_catalogue_de_formation'),

    # categories_de_documents
    path('categories_de_documents', categories_de_documents, name='categories_de_documents'),
    path('list_categories_de_documents', list_categories_de_documents, name='list_categories_de_documents'),
    path('add_categories_de_documents', add_categories_de_documents, name='add_categories_de_documents'),
    path('edit_categories_de_documents/<int:pk>', edit_categories_de_documents, name='edit_categories_de_documents'),
    path('del_categories_de_documents/<int:pk>', del_categories_de_documents, name='del_categories_de_documents'),

    # controles
    path('controles', controles, name='controles'),
    path('list_controles', list_controles, name='list_controles'),
    path('add_controles', add_controles, name='add_controles'),
    path('edit_controles/<int:pk>', edit_controles, name='edit_controles'),
    path('del_controles/<int:pk>', del_controles, name='del_controles'),

    # corps_de_controles
    path('corps_de_controles', corps_de_controles, name='corps_de_controles'),
    path('list_corps_de_controles', list_corps_de_controles, name='list_corps_de_controles'),
    path('add_corps_de_controles', add_corps_de_controles, name='add_corps_de_controles'),
    path('edit_corps_de_controles/<int:pk>', edit_corps_de_controles, name='edit_corps_de_controles'),
    path('del_corps_de_controles/<int:pk>', del_corps_de_controles, name='del_corps_de_controles'),

    # documents
    path('documents', documents, name='documents'),
    path('list_documents', list_documents, name='list_documents'),
    path('add_documents', add_documents, name='add_documents'),
    path('edit_documents/<int:pk>', edit_documents, name='edit_documents'),
    path('del_documents/<int:pk>', del_documents, name='del_documents'),

    # document

    # evaluations_impact_risque
    path('evaluations_impact_risque', evaluations_impact_risque, name='evaluations_impact_risque'),
    path('list_evaluations_impact_risque', list_evaluations_impact_risque, name='list_evaluations_impact_risque'),
    path('add_evaluations_impact_risque', add_evaluations_impact_risque, name='add_evaluations_impact_risque'),
    path('edit_evaluations_impact_risque/<int:pk>', edit_evaluations_impact_risque, name='edit_evaluations_impact_risque'),
    path('del_evaluations_impact_risque/<int:pk>', del_evaluations_impact_risque, name='del_evaluations_impact_risque'),

    # execution
    path('execution', execution, name='execution'),
    path('list_execution', list_execution, name='list_execution'),
    path('add_execution', add_execution, name='add_execution'),
    path('edit_execution/<int:pk>', edit_execution, name='edit_execution'),
    path('del_execution/<int:pk>', del_execution, name='del_execution'),

    # famille_de_risques
    path('famille_de_risques', famille_de_risques, name='famille_de_risques'),
    path('list_famille_de_risques', list_famille_de_risques, name='list_famille_de_risques'),
    path('add_famille_de_risques', add_famille_de_risques, name='add_famille_de_risques'),
    path('edit_famille_de_risques/<int:pk>', edit_famille_de_risques, name='edit_famille_de_risques'),
    path('del_famille_de_risques/<int:pk>', del_famille_de_risques, name='del_famille_de_risques'),

    # filiale

    # finalisation
    path('finalisation', finalisation, name='finalisation'),
    path('list_finalisation', list_finalisation, name='list_finalisation'),
    path('add_finalisation', add_finalisation, name='add_finalisation'),
    path('edit_finalisation/<int:pk>', edit_finalisation, name='edit_finalisation'),
    path('del_finalisation/<int:pk>', del_finalisation, name='del_finalisation'),

    # formation
    path('formation', formation, name='formation'),
    path('list_formation', list_formation, name='list_formation'),
    path('add_formation', add_formation, name='add_formation'),
    path('edit_formation/<int:pk>', edit_formation, name='edit_formation'),
    path('del_formation/<int:pk>', del_formation, name='del_formation'),

    # gestions_des_filiales
    path('gestions_des_filiales', gestions_des_filiales, name='gestions_des_filiales'),
    path('list_gestions_des_filiales', list_gestions_des_filiales, name='list_gestions_des_filiales'),
    path('add_gestions_des_filiales', add_gestions_des_filiales, name='add_gestions_des_filiales'),
    path('edit_gestions_des_filiales/<int:pk>', edit_gestions_des_filiales, name='edit_gestions_des_filiales'),
    path('del_gestions_des_filiales/<int:pk>', del_gestions_des_filiales, name='del_gestions_des_filiales'),

    # gravite_de_risques
    path('gravite_de_risques', gravite_de_risques, name='gravite_de_risques'),
    path('list_gravite_de_risques', list_gravite_de_risques, name='list_gravite_de_risques'),
    path('add_gravite_de_risques', add_gravite_de_risques, name='add_gravite_de_risques'),
    path('edit_gravite_de_risques/<int:pk>', edit_gravite_de_risques, name='edit_gravite_de_risques'),
    path('del_gravite_de_risques/<int:pk>', del_gravite_de_risques, name='del_gravite_de_risques'),

    # initialisation
    path('initialisation', initialisation, name='initialisation'),
    path('list_initialisation', list_initialisation, name='list_initialisation'),
    path('add_initialisation', add_initialisation, name='add_initialisation'),
    path('edit_initialisation/<int:pk>', edit_initialisation, name='edit_initialisation'),
    path('del_initialisation/<int:pk>', del_initialisation, name='del_initialisation'),

    # liste_de_documents

    # matrice_de_competence
    path('matrice_de_competence', matrice_de_competence, name='matrice_de_competence'),
    path('list_matrice_de_competence', list_matrice_de_competence, name='list_matrice_de_competence'),
    path('add_matrice_de_competence', add_matrice_de_competence, name='add_matrice_de_competence'),
    path('edit_matrice_de_competence/<int:pk>', edit_matrice_de_competence, name='edit_matrice_de_competence'),
    path('del_matrice_de_competence/<int:pk>', del_matrice_de_competence, name='del_matrice_de_competence'),

    # matrice_de_competence_param
    path('matrice_de_competence_param', matrice_de_competence_param, name='matrice_de_competence_param'),
    path('list_matrice_de_competence_param', list_matrice_de_competence_param, name='list_matrice_de_competence_param'),

services/models.py
from django.db import models

class Document(models.Model):
    fillale = models.CharField(max_length=255)
    annee_de_reference = models.CharField(max_length=255)
    systeme = models.CharField(max_length=255)
    processus = models.CharField(max_length=255)
    site = models.CharField(max_length=255)
    criticite_issue_de_la_cartographie_des_risques = models.CharField(max_length=255)
    annee_theorique_du_dernier_audit = models.CharField(max_length=255)
    annee_de_realisation = models.CharField(max_length=255)
    criticite_issue_de_la_mission_d_audit = models.CharField(max_length=255)
    annee_de_la_prochaine_mission_d_audit = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.fillale} - {self.annee_de_reference} - {self.systeme}"

services/activites/views.py
import json
import requests
from ..decorators import *
from django.contrib import messages
from apiRessource.endpointList import *
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse, JsonResponse


def activites(request):
    dropdown_activite_risque = 'True'
    activite_active = 'True'
    header_title= "Activités"
    breadcrumb = [
            {
                'name': 'Accueil',
                'path': reverse('services:home_superAdmin'),
            },
            {
                'name': 'activités et risques',
            },
            {
                'name': 'activités',
            },
        ]
    return render(request, 'services/activites/activites.html', locals())

def list_activites(request):
    get_data = requests.get(listeActivite)
    data_list = get_data.json()
    return render(request, "services/activites/list_activites.html", locals())

def edit_activites(request, pk):
    get_famillerisk = requests.get(f"{listeActivite}{pk}")
    data = get_famillerisk.json()
    if request.method == "POST":
        code_activite = request.POST.get('code_activite')
        # Données à envoyer dans la requête POST
        data = {
                "code_activite": code_activite,
                }
        # Faire une requête POST à l'API
        response = requests.put(f"{listeActivite}{pk}/", data=data)
        return HttpResponse(
            status=204,
            headers={
                'HX-Trigger': json.dumps({
                    "ListChanged": None,
                    "showMessage": f"famille de risque N°Modifié."
                })
            }
        )
    return render(request, "services/activites/form_activites.html", locals())

def add_activites(request):
    if request.method == "POST":
        code_activite = request.POST.get('code_activite')
        # Données à envoyer dans la requête POST
        data = {
                "code_activite": code_activite,
                }
        # Faire une requête POST à l'API
        response = requests.post(f"{listeActivite}", data=data)
        return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "ListChanged": None,
                        "showMessage": f"Enregistrement ajouter."
                    })
                }
            )
    return render(request, "services/activites/form_activites.html", locals())

def del_activites(request, pk):
    get_famillerisk = requests.get(f"{listeActivite}{pk}")
    data = get_famillerisk.json()
    if request.method == "POST":
        response = requests.delete(f"{listeActivite}{pk}")
        return HttpResponse(
        status=204,
        headers={
            'HX-Trigger': json.dumps({
                "ListChanged": None,
                "showMessage": f"enregistrement Supprimé."
            })
        })
    return render(request, "services/activites/del_activites.html", locals())

services/auditeurs/views.py
import json
import requests
from ..decorators import *
from django.contrib import messages
from apiRessource.endpointList import *
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse


def auditeurs(request):
    return render(request, 'services/auditeurs/auditeurs.html', locals())

def list_auditeurs(request):
    get_data = requests.get(typemission)
    data_list = get_data.json()
    return render(request, "services/auditeurs/list_auditeurs.html", locals())

def edit_auditeurs(request, pk):
    get_famillerisk = requests.get(f"{listefamillerisk}{pk}")
    data = get_famillerisk.json()
    if request.method == "POST":
        value = request.POST.get('libfamillerisk')
         # Données à envoyer dans la requête POST
        data = {
                "libfamillerisk": f"{value}"
                }
        # Faire une requête POST à l'API
        response = requests.put(f"{listefamillerisk}{pk}/", data=data)
        return HttpResponse(
            status=204,
            headers={
                'HX-Trigger': json.dumps({
                    "ListChanged": None,
                    "showMessage": f"famille de risque N°Modifié."
                })
            }
        )
    return render(request, "services/auditeurs/form_auditeurs.html", locals())

def add_auditeurs(request):
    if request.method == "POST":
        value = request.POST.get('libfamillerisk')
         # Données à envoyer dans la requête POST
        data = {
                "libfamillerisk": f"{value}"
                }
        # Faire une requête POST à l'API
        response = requests.post(f"{listefamillerisk}", data=data)
        return HttpResponse(
                status=204,
                headers={
                    'HX-Trigger': json.dumps({
                        "ListChanged": None,
                        "showMessage": f"Enregistrement ajouter."
                    })
                }
            )
    return render(request, "services/auditeurs/form_auditeurs.html", locals())

def del_auditeurs(request, pk):
    get_famillerisk = requests.get(f"{listefamillerisk}{pk}")
    data = get_famillerisk.json()
    if request.method == "POST":
        response = requests.delete(f"{listefamillerisk}{pk}")
        return HttpResponse(
        status=204,
        headers={
            'HX-Trigger': json.dumps({
                "ListChanged": None,
                "showMessage": f"enregistrement Supprimé."
            })
        })
    return render(request, "services/auditeurs/del_auditeurs.html", locals())


services/gestions_des_filiales/views.py
import json
import requests
from ..decorators import *
from django.contrib import messages
from apiRessource.endpointList import *
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse

services/liste_de_documents/views.py
import json
import requests
from ..decorators import *
from django.contrib import messages
from apiRessource.endpointList import *
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse

templates/services/execution/del_execution.html
<div class="modal-header">
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="btn-close"></button>
</div>
<div class="modal-body">
    <div class="mt-2 text-center">
        <lord-icon src="https://cdn.lordicon.com/gsqxdxog.json" trigger="loop" colors="primary:#f7b84b,secondary:#f06548" style="width:100px;height:100px"></lord-icon>
        <div class="mt-4 pt-2 fs-15 mx-4 mx-sm-5">
            <h4>Supprimer - {{ data.libfamillerisk }} ?</h4>
            <p class="text-muted mx-4 mb-0">êtes-vous sûr de vouloir supprimer cette enregistrement ?</p>
        </div>
    </div>
    <div class="d-flex gap-2 justify-content-center mt-4 mb-2">
        <button type="button" class="btn w-sm btn-light" data-bs-dismiss="modal">Fermer</button>
        <button type="button" data-bs-dismiss="modal" class="btn w-sm btn-danger " id="delete-record" hx-indicator="#loader" hx-target="#dialog" hx-headers='{"X-CSRFToken":"{{ csrf_token }}"}' hx-post="{% url 'services:del_famille_de_risques' pk=data.idfamillerisk %}">Supprimer!</button>
    </div>
</div>

templates/services/execution/execution.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Exécution | BGFI {% endblock title %}
{% block special_css %}
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
{% endblock special_css %}

{% block content %}
    <section class="content mx-2">
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3 ">
                <div class="row">
                    <div class="col">
                        <h6 class="m-0 font-weight-bold text-primary">Exécution</h6>
                    </div>
                    <div class="col">
                        <button class="btn btn-success btn-sm float-right" hx-get="{% url 'services:add_execution' %}" hx-target="#dialog"><i class="ri-add-line align-bottom me-1"></i>Ajouter</button>
                    </div>
                </div>
            </div>
            <div class="card-body" hx-get="{% url 'services:list_execution' %}" hx-trigger="load, ListChanged from:body" hx-target="this" hx-indicator="#loader">
                <div class="row justify-content-center center htmx-indicator" id="loader">
                    <div class="spinner-border text-primary" role="status">
                        <span class="sr-only">chargement ...</span>
                    </div>
                </div>
            </div>
        </div>
        {% comment %} <button hx-get="{% url 'account:add_user' %}" hx-target="#dialog" class="btn btn-primary">
            Ajouter un utilisateur
        </button> {% endcomment %}
    </section>
{% endblock %}

{% block special_js %}
    <!-- DataTables  & Plugins -->
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
    <script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/datatables-demo.js' %}"></script>
    <script>
        $(function () {
            $('#execution').DataTable({
                "paging": true,
                "lengthChange": true,
                "lengthMenu": [ [5, 10, 25, 50, -1], [5, 10, 25, 50, "Tous"] ],
                "searching": true,
                "ordering": false,
                "info": true,
                "autoWidth": true,
                "responsive": true,
                language: {
                    processing:     "Traitement en cours...",
                    search:         "Rechercher&nbsp;:",
                    lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
                    info:           "Affichage de _START_ &agrave; _END_ sur _TOTAL_",
                    infoEmpty:      "Affichage de 0 &agrave; 0 sur 0",
                    infoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                    infoPostFix:    "",
                    loadingRecords: "Chargement en cours...",
                    zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
                    emptyTable:     "Aucune donnée disponible dans le tableau",
                    paginate: {
                        first:      "Premier",
                        previous:   "Pr&eacute;c&eacute;dent",
                        next:       "Suivant",
                        last:       "Dernier"
                    },
                    aria: {
                        sortAscending:  ": activer pour trier la colonne par ordre croissant",
                        sortDescending: ": activer pour trier la colonne par ordre décroissant"
                    }
                }
            });
        });
    </script>
{% endblock special_js %}

templates/services/execution/form_execution.html
{% load static %}
<div class="modal-header bg-light p-3">
    <h5 class="modal-title" id="exampleModalLabel"></h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="close-modal"></button>
</div>
<form>
    {% csrf_token %}
    <div class="modal-body">
        <div class="mb-3" id="modal-id">
            <label for="libfamillerisk" class="form-label">Famille de Risque </label>
            <input type="text" id="libfamillerisk" name="libfamillerisk" value="{{data.libfamillerisk}}" class="form-control" placeholder="Famille de rique" />
        </div>
    </div>
    <div class="modal-footer">
        <div class="hstack gap-2 justify-content-end">
            <button type="button" class="btn btn-light" data-bs-dismiss="modal">Fermer</button>
            {% if not data %}
                <button type="submit" data-bs-dismiss="modal" class="btn btn-success" id="add-btn" hx-post="{% url 'services:add_famille_de_risques' %}" hx-indicator="#loader">Ajouter</button>
            {% else %}
                <button type="button" data-bs-dismiss="modal" class="btn btn-success" hx-post="{% url 'services:edit_famille_de_risques' pk=data.idfamillerisk %}" hx-indicator="#loader" hx-target="#dialog" id="edit-btn">modifier</button>
            {% endif %}
        </div>
    </div>
</form>

templates/services/execution/list_execution.html
{% for item in data_list %}
    <tr  id="movie-{{ item.pk }}">
        <th scope="row">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="chk_child" value="option1">
            </div>
        </th>
        <td class="align-middle">{{ item.libfamillerisk }}</td>
        <td>
            <div class="d-flex gap-2">
                <div class="edit">
                    <button class="btn btn-success btn-sm" hx-get="{% url 'services:edit_famille_de_risques' pk=item.idfamillerisk %}" hx-target="#dialog">Modifier</button>
                </div>
                <div class="remove">
                    <button class="btn btn-sm btn-danger remove-item-btn" hx-get="{% url 'services:del_famille_de_risques' pk=item.idfamillerisk %}" hx-target="#dialog" >Supprimer</button>
                </div>
            </div>
        </td>
    </tr>
{% endfor %}